import Head from 'next/head'
import styles from 'api/styles/Home.module.css'
import {data} from './data'
import { HostGrid } from 'api/Components/HostGrid'

export default function Home({ profiles }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HostGrid data={profiles} />
      </main>
    </>
  )
}

export async function getStaticProps() {
  const profiles = data;

  return {
    props: { profiles }
  };
}
